feat(console): unsaved changes alert
logto-io/logto pull request #1409
Opened 2022-07-04 12:30 UTC by xiaoyijun

## Summary

feat(console): unsaved changes alert

### Note
React-Router V6 has removed the `useBlocker` & `usePrompt` API, so I implemented a workaround solution to support this feature. 

### Todo
- Refactor & Add unsaved changes alert for user settings
- Refactor & Add unsaved changes alert for connector details

## Testing

![SaveAlert](https://user-images.githubusercontent.com/10806653/177154951-4967f29c-30ba-498b-a136-bc9ad0b9da47.gif)

2022-07-04 13:03 UTC, gao-sun requested changes
your pnpm lock file looks not right

2022-07-05 05:33 UTC, wangsijie reviewed
return JSX in hooks is not a common practice?

2022-07-05 06:25 UTC, wangsijie approved these changes

2022-07-05 07:00 UTC, gao-sun commented on packages/console/src/components/UnsavedChangesAlertModal/index.tsx
> +import { Blocker, Transition } from 'history';
```suggestion
import type { Blocker, Transition } from 'history';
```

2022-07-05 07:02 UTC, gao-sun commented on packages/phrases/src/locales/zh-cn.ts
> +      unsaved_changes_warning: '你有未保存的更改, 确定要离开吗？',
```suggestion
      unsaved_changes_warning: '还有未保存的变更, 确定要离开吗？',
```

2022-07-05 07:02 UTC, gao-sun approved these changes

2022-07-05 09:09 UTC, merged