feat(schema): update application db
logto-io/logto pull request #169
Opened 2022-01-10 08:09 UTC by simeng-li

## Summary

Update application DB

1. add optional field `description`
2. add optional field `logo_uri` to the `oidc_client_metadata`. As supported by the OIDC provider
3. add `idTokenTTL` with a default value
4. add `refreshTokenTTL` with a default value
5. remove the `application_type` field in `oidc_client_metadata` in order to keep a single source of truth of the application type
6. Update the OIDC provider adapter, load the application type from the ApplicationDB's type field directly 
7. Update the `buildOidcClientMetadata` util methods accordingly. 

## Testing

test locally on playground. 
public db updated accordingly. 
UT passed 

@logto-io/eng

2022-01-10 09:11 UTC, gao-sun requested changes

2022-01-10 09:11 UTC, gao-sun commented on packages/schemas/tables/applications.sql
> +  refresh_token_ttL bigint not null default(2592000),
typo: ttl (lowercase l)

2022-01-10 10:40 UTC, simeng-li commented on packages/schemas/tables/applications.sql
> +  refresh_token_ttL bigint not null default(2592000),
done thx

2022-01-11 03:18 UTC, wangsijie approved these changes
LGTM

2022-01-11 03:28 UTC, darcyYe commented on packages/schemas/src/foundations/jsonb-types.ts
> +  logoUri: z.string().optional(),
nit: [zod string](https://github.com/colinhacks/zod#strings) has a built-in URL constraint. should we take advantage of this?

2022-01-11 03:29 UTC, darcyYe approved these changes
LGTM

2022-01-11 03:58 UTC, gao-sun approved these changes

2022-01-11 03:58 UTC, merged