chore(connector-core,core,phrases): use try catch on JSON.parse
logto-io/logto pull request #1857
Opened 2022-09-01 09:29 UTC by darcyYe

## Summary

Use try catch on JSON.parse to avoid unexpected behaviors.

## Testing

UTs.

2022-09-01 16:35 UTC, gao-sun requested changes
wrong base?

2022-09-02 06:56 UTC, wangsijie commented
@darcyYe could you provide more info on why wrapping every JSON.parse?

2022-09-02 07:40 UTC, wangsijie commented on packages/connector-core/src/index.ts
> +  payload?: unknown
maybe something like `errorPayload`?

2022-09-02 07:40 UTC, wangsijie approved these changes
Overall LGTM

2022-09-02 07:44 UTC, darcyYe commented on packages/connector-core/src/index.ts
> +  payload?: unknown
updated.

2022-09-05 10:20 UTC, gao-sun approved these changes

2022-09-05 18:40 UTC, merged