feat: add vertical center support
logto-io/logto pull request #2032
Opened 2022-09-29 22:27 UTC by FlurryNight

## Summary
This PR adds vertical center support in usePosition hook (#1852)

The tooltip can be flipped to `'right' | 'left'` and the tail points correctly.

See the following examples
#### Left Tooltip
 - `<Tooltip verticalAlign='center' horizontalAlign='end' flip='left' anchorRef={tipRef} content={t(tooltip)} />`
 
#### Right Tooltip
 - `<Tooltip verticalAlign='center' horizontalAlign='start' flip='right' anchorRef={tipRef} content={t(tooltip)} />`

#### I think I got it correct, let me know if I did smth wrong, UI is not my best. Also, sorry for the huge delay, been busy and my dev environment on windows was a little buggy.

## Testing
Locally Tested
![logto-tail-left](https://user-images.githubusercontent.com/47457170/193224596-71f65e52-2fee-418f-affe-9519d154f4ae.png)
![logto-tail-right](https://user-images.githubusercontent.com/47457170/193224601-7a0dcdfb-4f3f-45b7-9891-591ab6987fcc.png)

2022-10-02 06:17 UTC, charIeszhao commented
Awesome, @FlurryNight 
We are currently celebrating the national holidays this entire week, so a delay will be expected to have it reviewed.

Sorry about that and thank you again for your contribution and huge support!

Best,
Charles

2022-10-08 02:48 UTC, wangsijie commented
hi @FlurryNight 
Overall looks good to me! Would you like to fix the lint issues? Most of them can be auto fixed by `--fix`.

2022-10-08 03:25 UTC, wangsijie commented
@FlurryNight no problem, and let's wait for another approval before merge.

2022-10-08 03:25 UTC, wangsijie approved these changes

2022-10-08 03:26 UTC, charIeszhao commented
I'll take a look and help fix the lint issues. No worries @FlurryNight

2022-10-08 03:37 UTC, charIeszhao commented on packages/console/src/components/Tooltip/index.module.scss
> +    left: 0% !important;
We prefer not to use `!important`. I'll take a look if this is necessary and can be avoided

2022-10-08 03:43 UTC, wangsijie requested changes
The `!important` is not allowed in our rules, could you find another way?

2022-10-09 02:04 UTC, wangsijie approved these changes
LGTM

2022-10-10 15:53 UTC, merged