feat(core): sign in with email
logto-io/logto pull request #209
Opened 2022-01-29 08:05 UTC by wangsijie

## Summary

Sign in with email (and passcode).

`POST /session`

if no `code` in body, send passcode.

else, verify passcode and sign in.

## Linear Issue Reference

LOG-865

## Testing

Local test:

### received code in email

![image](https://user-images.githubusercontent.com/5717882/151653066-4295c794-349d-4632-a09c-5102eadd2d24.png)

### sign in success

![image](https://user-images.githubusercontent.com/5717882/151653053-d7b769de-af6a-4750-8421-91a7b64e8fd8.png)

2022-01-29 16:29 UTC, darcyYe requested changes

2022-01-29 16:29 UTC, darcyYe commented on packages/core/src/utils/regex.ts
> +export const emailReg = /^\S+@\S+\.\S+$/;
another thing that needs to be mentioned is email addresses are usually not case-sensitive and should be converted to lowercase or uppercase before inserting to DB. not sure whether we have done this. would you mind double-checking this?

2022-01-30 06:17 UTC, wangsijie commented on packages/core/src/utils/regex.ts
> +export const emailReg = /^\S+@\S+\.\S+$/;
Since we have passcode verification, I think there is no need to do such "strict" email address check.

2022-01-30 06:33 UTC, wangsijie commented on packages/core/src/routes/session.ts
> +        code: string().optional(),
After refactor, those guard is move into matched sign in method function.

2022-01-30 06:33 UTC, wangsijie commented on packages/core/src/lib/user.ts
> +export const signInWithUsernameAndPassword = async (
updated

2022-01-30 06:39 UTC, darcyYe commented
LGTM

2022-01-30 06:42 UTC, darcyYe approved these changes

2022-01-31 03:04 UTC, merged