feat: support png and jpeg files for connector logo
logto-io/logto pull request #2758
Opened 2022-12-29 06:48 UTC by darcyYe

## Summary

Support png and jpeg file for connector logo.

## Testing

Tested locally with png and jpeg connector logo files. Logos, config templates and README files can display properly.
<img width="3008" alt="image" src="https://user-images.githubusercontent.com/15182327/209914412-8ea1d9ae-9710-41f1-99fe-1c52fb0cdb17.png">
<img width="3008" alt="image" src="https://user-images.githubusercontent.com/15182327/209914544-65ad8d96-a30d-484d-a3e4-6dd37a884520.png">
<img width="391" alt="image" src="https://user-images.githubusercontent.com/15182327/209914446-8f9bd7b9-8a1f-45d6-b5cd-1c1b579a88bc.png">

2022-12-30 02:40 UTC, wangsijie commented on packages/core/src/connectors/utilities/index.ts
> +const getUrlType = (url: string): UrlType => {
Maybe regex can make this funciton more readable

2022-12-31 14:52 UTC, charIeszhao commented on packages/core/src/connectors/utilities/index.ts
> +type UrlType = 'text' | 'svg' | 'png' | 'jpeg' | undefined;
Don't forget `jpg`

2023-01-03 06:39 UTC, charIeszhao commented on packages/core/src/connectors/utilities/index.ts
> +  const extension = splitBaseUrl && splitBaseUrl.length > 1 ? splitBaseUrl.slice(-1)[0] : undefined;
If we only wants to get the extension, we can use `.lastIndexOf('.')`

2023-01-04 02:48 UTC, simeng-li requested changes
Let's add ut for those utility methods.

2023-01-13 05:54 UTC, closed without merging