refactor(core): encode filename part in URL generated by image service
logto-io/logto pull request #4169
Opened 2023-07-14 08:34 UTC by darcyYe

## Summary

encode filename part in URL generated by image service.

In the URL returned by Logto's image service when uploading a file, the file name is appended at the end. The file name may contain some characters that are encoded differently from the original string by encodeUri. This can cause situations where the logo cannot be accessed when using the URL as the img source in an email template (some email services will serve the logo urls in emails on their own servers, which will encode the image URL we put in the email template, leading to failed access. We need to encode the image URL ourselves before putting it in the email template).
Many email services do not accept SVG. So to avoid this issue, we need to exclude SVG files when uploading images.

Here comes two changes to fix the aforementioned issues:
1. encode filename part in URL returned by Logto image service.
2. enable the customization on accepting image format for `<ImageFileUploader />` component. And restrict the logo uploaded for email branding to be in `png`, `jpg` or `jpeg` format.

## Testing

Tested locally, can not upload SVG image and the image with space in its file name can successfully show up in email content.

## Checklist

- [ ] `.changeset`
- [ ] unit tests
- [ ] integration tests
- [ ] docs

OR

- [ ] This PR is not applicable for the checklist

2023-07-14 08:58 UTC, gao-sun commented on packages/console/src/ds-components/Uploader/ImageUploader/index.tsx
> +        conditional((allowedMimeTypes ?? []).length > 0 && allowedMimeTypes) ??
```suggestion
        Boolean(allowedMimeTypes?.length) ? allowedImageMimeTypes : allowedMimeTypes
```

2023-07-14 08:58 UTC, gao-sun commented on packages/console/src/ds-components/Uploader/ImageUploader/index.tsx
> +        allowedImageMimeTypes
```suggestion
        Boolean(allowedMimeTypes?.length) ? allowedImageMimeTypes : allowedMimeTypes
```

2023-07-14 08:59 UTC, gao-sun commented on packages/console/src/ds-components/Uploader/ImageUploaderField/index.tsx
> +    extensions: convertToFileExtensionArray(allowedMimeTypes ?? allowedImageMimeTypes),
no need to fall back everywhere? just do it once

2023-07-14 09:09 UTC, gao-sun commented on packages/core/src/utils/storage/utils.ts
> +  )}`;
```suggestion
  const splitter = fullPath.split('/');
  const filename = splitted.at(-1);

  return filename ? [...splitter, encodeURIComponent(filename)].join('/') : fullPath;
```

2023-07-14 09:10 UTC, gao-sun commented on packages/core/src/utils/storage/utils.ts
> +export const fileNameURLEncoder = (url: string): string => {
```suggestion
export const fileNameUrlEncoder = (url: string): string => {
```

2023-07-14 09:10 UTC, gao-sun commented on packages/core/src/utils/storage/utils.ts
> +export const fileNameURLEncoder = (url: string): string => {
also we should add unit tests for this

2023-07-15 04:08 UTC, gao-sun approved these changes

2023-07-16 13:03 UTC, wangsijie requested changes

2023-07-16 13:03 UTC, wangsijie commented on packages/core/src/routes/user-assets.ts
> +          url: fileNameUrlEncoder(rawUrl),
I think we should do the encode in Console, the response url is already valid?

2023-07-17 03:49 UTC, wangsijie commented on packages/connectors/connector-logto-email/src/utils.ts
> +export const fileNameUrlEncoder = (url: string): string => {
use `encodeURI`?

2023-07-17 05:36 UTC, wangsijie approved these changes

2023-07-17 05:38 UTC, merged