feat(console): delete connector
logto-io/logto pull request #433
Opened 2022-03-22 06:03 UTC by wangsijie

## Summary

Add feature: delete connector. Though the label is "delete", but actually it will be "disabled".

## Linear Issue Reference

LOG-1896

## Testing

<img width="259" alt="截屏2022-03-22 下午1 59 55" src="https://user-images.githubusercontent.com/5717882/159417892-bb531603-6abb-4d9e-a36a-56cf0f0d8837.png">

2022-03-22 06:52 UTC, simeng-li approved these changes
LGTM

2022-03-22 08:34 UTC, xiaoyijun commented on packages/console/src/pages/ConnectorDetails/index.tsx
> +
Need a toast on delete succeeded.

2022-03-22 08:37 UTC, xiaoyijun requested changes

2022-03-22 08:37 UTC, xiaoyijun commented on packages/console/src/pages/ConnectorDetails/index.tsx
> +
Need a toast on delete succeeded.

2022-03-23 03:26 UTC, wangsijie commented on packages/console/src/pages/ConnectorDetails/index.tsx
> +
updated

2022-03-23 03:34 UTC, xiaoyijun approved these changes

2022-03-23 03:48 UTC, merged