feat(console): add paginations for applications and resources
logto-io/logto pull request #495
Opened 2022-04-02 13:11 UTC by xiaoyijun

## Summary

* add paginations for applications and resources
* show paginations only if the total data count is bigger than the page size

## Linear Issue Reference

None.

## Testing

Tested in the admin console.

2022-04-06 05:58 UTC, IceHe commented on packages/console/src/pages/ApiResources/index.tsx
> +        {totalCount !== undefined && totalCount > pageSize && (
`!!totalCount && totalCount > pageSize` simplier?

2022-04-06 05:58 UTC, IceHe commented on packages/console/src/pages/Applications/index.tsx
> +        {totalCount !== undefined && totalCount > pageSize && (
ditto

2022-04-06 06:12 UTC, wangsijie requested changes

2022-04-06 06:12 UTC, wangsijie commented on packages/console/src/pages/ApiResources/index.tsx
> +  const [pageIndex, setPageIndex] = useState(1);
Considering rebase #493 and remove `useState`.

2022-04-06 06:13 UTC, wangsijie commented
And I think we may need to show pagination even if total page count is 1. Better notice our designer before merging.

2022-04-06 07:18 UTC, simeng-li approved these changes
overall LGTM please make sure resolve the conversations before merge

2022-04-07 12:20 UTC, IceHe approved these changes
Overall LGTM

2022-04-07 12:36 UTC, wangsijie approved these changes

2022-04-07 12:36 UTC, merged