fix(core): forgot password on the first access of migrated users
logto-io/logto pull request #6642
Opened 2024-09-28 13:22 UTC by GeisonPiegas

## Summary
This pull request fixes a bug that occurred when users were migrated from the old system to Logto ([migration guide](https://docs.logto.io/docs/recipes/migrations/)) using a different password encryption method than Argon2i. The issue caused a 500 error when users attempted to reset their password for the first time using the "Forgot my password" option. The error was due to a missing validation step where the system was incorrectly comparing the new password with the old one, despite the previous password being encrypted with a different method (not Argon2i).

## Testing
Manual testing was conducted by creating user accounts with various encryption methods, resetting passwords, and verifying system behavior.

## Checklist
- [ ] `.changeset`
- [ ] unit tests
- [ ] integration tests
- [ ] necessary TSDoc comments

2024-09-29 01:39 UTC, wangsijie approved these changes

2024-09-29 02:33 UTC, wangsijie requested changes
Thanks for your contribute, would you mind fixing the code style and adding some comments as I suggested?

2024-09-29 02:33 UTC, wangsijie commented on packages/core/src/routes/interaction/verifications/profile-verification.ts
>    assertThat(
```suggestion
  // Only compare password if the encryption method (algorithm) is Argon2i
  // if the user is migrated, this check will be skipped
  assertThat(
    !oldPasswordEncrypted ||
      passwordEncryptionMethod !== UsersPasswordEncryptionMethod.Argon2i ||
      !(await argon2Verify({ password: passwordProfile.password, hash: oldPasswordEncrypted })),
    new RequestError({ code: 'user.same_password', status: 422 })
  );
```

2024-09-29 02:39 UTC, simeng-li commented
Might also need to fix the UT. Or could you please turn on the maintainer's edit permission? We could fix it. Thx

2024-09-29 17:32 UTC, GeisonPiegas commented
@wangsijie, I made the requested changes.
@simeng-li sorry, the Pull Request was created from a new branch within the main repository, not from a fork. Because of this, I don’t have the option to enable "Allow edits from maintainers."
How would you prefer to proceed? Should I share the repository with you, or would it be better to open a new PR from a fork to allow edits?

2024-09-30 03:57 UTC, wangsijie commented
@GeisonPiegas It is OK for now

2024-09-30 04:08 UTC, wangsijie commented
@GeisonPiegas One last thing, fix the unit test by changing the mock response:

```ts
const findUserById = jest.fn().mockResolvedValue({
  id: 'foo',
  passwordEncrypted: 'passwordHash',
  passwordEncryptionMethod: UsersPasswordEncryptionMethod.Argon2i,
});
```

2024-10-01 01:44 UTC, wangsijie commented
@GeisonPiegas some commits can not pass the commitlint check, maybe you can squash all commits into a single one that meets the requirement.

2024-10-01 03:04 UTC, GeisonPiegas commented
@wangsijie I'm sorry, I've squashed the commits into a single one.

2024-10-08 03:41 UTC, wangsijie approved these changes

2024-10-08 03:42 UTC, wangsijie commented
@GeisonPiegas You need to sign the commit, after you configuring a GPG key, you can re-commit with `-S` option and then force push.

2024-10-10 01:39 UTC, GeisonPiegas commented
Sorry @wangsijie, I forgot to configure the signature. I've corrected it, and the commit is now signed.

2024-10-11 02:12 UTC, merged