docs: kotlin core api reference(zh-cn)
logto-io/logto pull request #762
Opened 2022-05-09 05:56 UTC by xiaoyijun

## Summary

* docs: kotlin core api reference(zh-cn)
* update kotlin core sdk reference

## Linear Issue Reference

* LOG-2278

## Testing

<img width="426" alt="image" src="https://user-images.githubusercontent.com/10806653/167348859-196ca892-7ace-44f7-921f-d9b0827d1090.png">

2022-05-09 07:08 UTC, IceHe commented on packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-refresh-token-token-response/index.md
> +| | |
Empty Header?

2022-05-09 07:08 UTC, IceHe commented on packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-oidc-config-response/index.md
> +| | |
Empty header?

2022-05-09 07:08 UTC, IceHe commented on packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-id-token-claims/index.md
> +| | |
empty header?

2022-05-09 07:08 UTC, IceHe commented on packages/docs/i18n/zh-cn/docusaurus-plugin-content-docs/current/sdk/Kotlin/kotlin/io.logto.sdk.core.type/-code-token-response/index.md
> +| | |
empty header?

2022-05-10 04:49 UTC, IceHe approved these changes
lgtm

2022-05-10 04:52 UTC, demonzoo commented
Is this auto generated by a tool? If yes, then I won't bother going into the details (TL;DR)

2022-05-10 05:19 UTC, xiaoyijun commented
> Is this auto generated by a tool? If yes, then I won't bother going into the details (TL;DR)

Yes. @demonzoo 
Reference: https://github.com/Kotlin/dokka

2022-05-10 05:49 UTC, demonzoo approved these changes

2022-05-10 07:28 UTC, gao-sun requested changes
should be 2 PRs for reorg and doc adding?

2022-05-10 07:43 UTC, gao-sun approved these changes
lets separate next time

2022-05-10 07:44 UTC, merged